### ISSUE TITLE
Could not start resourced-master

### ISSUE THREAD

**Issue by beeyeas** [resourced/resourced-master#3]
When i download resourced-master binary and try start 

ERROR 42704: type "jsonb" does not exist in line 24, column 10:

20: CREATE TABLE hosts (
21:     id BIGSERIAL PRIMARY KEY NOT NULL,
22:     access_token_id bigint REFERENCES access_tokens (id),
23:     name TEXT NOT NULL,
24:     tags JSONB,
25:     data JSONB
26: );
27: 
28: CREATE INDEX idx_name on hosts (name);
29:

**Comment by didip** [comment]
Ah, you need PostgreSQL 9.4.x

**Comment by beeyeas** [comment]
Cool, it works. Could you please update README

**Comment by didip** [comment]
Yup: https://github.com/resourced/resourced-master#installation-for-users
